import os
import argparse


#Load in all known materials
materialSet = {}
 
for targetMaterialFile in ["MaterialSet.csv", "surface-pmfp/MaterialSetPMFP.csv"]:
    if not os.path.exists(targetMaterialFile):
        continue
    materialFile = open(targetMaterialFile,"r")
    for line in materialFile:
        if line[0] == "#":
            continue
        lineTerms = line.split(",")
        if len(lineTerms)<4:
            print("Problem reading material line: ", line)
            continue
        materialSet[ lineTerms[0]] = [lineTerms[1],lineTerms[2],int(lineTerms[3])]
        
if len( materialSet.keys() ) == 0:
    print("No materials found. Please try again")
    quit()        
        
print(materialSet)
parser = argparse.ArgumentParser(description="Parameters for UA Config File Generation")
parser.add_argument('--operation-type', required = True, choices = ['pdb' , 'pdb-folder'], type = str, help = 'Currently only \'pdb\' or pdb-folder are valid')
parser.add_argument("-p","--input-file",  required=True, help="Path to protein PDB file")
parser.add_argument("-r","--radius", type=float,required=True,help="NP radius [nm]")
parser.add_argument("-z","--zeta", type=float, required=True,  help="NP zeta potential [V]")
parser.add_argument("-o","--outputfolder", default="UAOutput", help="Working folder for results")
parser.add_argument("-m","--material", required=True, choices =  materialSet.keys() ,help="Chosen material")
parser.add_argument("-P", "--postprocess",default = 1, help="Post-process results")
parser.add_argument("-b","--beadset",default="beadsets/StandardAABeadSet.csv", help="Bead parameter file")
parser.add_argument("-c","--configloc",default="", help="Location to save the generated configuration file")
args = parser.parse_args()




canRun = 0
if args.material in materialSet:
    pmfFolder,hamakerFile,shape = materialSet[ args.material]
    canRun = 1
else:
    print("An error has occured, cancelling run. Please check material name again.")
    print("Input material: ", args.material)
    print("Known materials: ", materialSet.keys)
    quit()

beadSetFile = open(args.beadset,"r")
beadNames = []
beadCharges = []
beadRadii = []
useDefaultBeadSet = 0
for line in beadSetFile:
    if line[0]=="#":
        continue
    lineTerms = line.strip().split(",")
    if len(lineTerms) < 3:
        print("Could not read line", line)
        continue
    beadNames.append(lineTerms[0])
    beadCharges.append(lineTerms[1])
    beadRadii.append(lineTerms[2])


if len(beadNames) == 0:
    print("No AA beads found in file, attempting with default parameters")
    useDefaultBeadSet = 1
if len(beadNames)!=len(beadCharges) or len(beadNames)!=len(beadRadii):
    print("Mismatch between number of bead parameters, check input. Attempting with default parameters")
    useDefaultBeadSet = 1
beadNameString = ", ".join(beadNames)
beadChargeString = ", ".join( [ str(round(float(a),3)) for a in beadCharges])
beadRadiiString = ", ".join( [ str( round(float(a),3)) for a in beadRadii])

configOutputName = "uaconfigautogen.config"


def writeConfigFile(configOutputLoc):
    outputConfigFile = open(configOutputLoc,"w")
    outputConfigFile.write("#Autogenerated UA Config file\n")
    outputConfigFile.write("output-directory = "+args.outputfolder+"\n")
    outputConfigFile.write("pdb-target = "+args.input_file+"\n")
    outputConfigFile.write("nanoparticle-radius = [" + str(args.radius)+"]\n")
    outputConfigFile.write("np-type = " + str(shape)+"\n")
    outputConfigFile.write("pmf-directory = " + pmfFolder + "\n")
    outputConfigFile.write("hamaker-file = " + hamakerFile + "\n")
    outputConfigFile.write("enable-surface \nenable-core \nenable-electrostatic \nsimulation-steps = 2000 \npotential-cutoff=5.0 \npotential-size = 1000 \nangle-delta = 5.0 \nbjerum-length=0.751 \ndebye-length=0.766 \n")
    outputConfigFile.write("zeta-potential = [" + str(args.zeta) + "] \n")
    if useDefaultBeadSet == 1:
        outputConfigFile.write("amino-acids         = [ ALA, ARG, ASN, ASP, CYS, GLN, GLU, GLY, HIS, ILE, LEU, LYS, MET, PHE, PRO, SER, THR, TRP, TYR, VAL] \n")
        outputConfigFile.write("amino-acid-charges  = [ 0.0, 1.0, 0.0, -1.0, 0.0, 0.0, -1.0, 0.0, 0.5, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ] \n")
        outputConfigFile.write("amino-acid-radii    = [ 0.323, 0.429, 0.362, 0.356, 0.352, 0.386, 0.376, 0.285, 0.302, 0.401, 0.401, 0.405, 0.402, 0.421, 0.362, 0.328, 0.357, 0.449, 0.425, 0.377] \n")
    else:
        outputConfigFile.write("amino-acids         = [ "+beadNameString+"] \n")
        outputConfigFile.write("amino-acid-charges  = [ "+beadChargeString+"] \n")
        outputConfigFile.write("amino-acid-radii    = [ "+beadRadiiString+"] \n")
    outputConfigFile.close()
writeConfigFile(configOutputName)
if args.configloc != "":
    writeConfigFile(args.configloc+"/"+configOutputName)


print("Generated config file, running UA")
os.system("./UnitedAtom --config-file=uaconfigautogen.config")
print("UA run complete")

if args.postprocess == 1 and args.operation_type=="pdb":
    proteinTargetName = (args.input_file.split("/")[-1])[:-4]
    if shape==1:
        uaResultFileNameOriginal = proteinTargetName+"_"+str(int(args.radius))+"_"+str(int(1000*args.zeta))+".uam"
    else:
        uaResultFileNameOriginal = proteinTargetName+"_"+str(int(args.radius))+"_"+str(int(1000*args.zeta))+"_0.uam"
    uaResultFileName = proteinTargetName+"_"+args.material+"_"+str(args.radius)+"_"+str(args.zeta)+".uam"
    os.system("mv "+args.outputfolder+"/"+uaResultFileNameOriginal+" "+ args.outputfolder+"/"+uaResultFileName)
    print("Generating heatmap")
    os.system("python3 tools/plotmap "+ args.outputfolder+"/"+uaResultFileName)
    print("Generating rotated PDB")
    os.system("python3 tools/ApplyOptimumRotation.py -p " + args.input_file + " -u " + args.outputfolder+"/"+uaResultFileName + " -o "+args.outputfolder)



